apiVersion: v1
kind: Service
metadata:
  name: fsdp-t5-training-master
spec:
  selector:
    job-name: fsdp-t5-training-master
  ports:
    - protocol: TCP
      port: 29500  
      targetPort: 29500
  clusterIP: None  # Headless Service
---
apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: fsdp-t5-training
spec:
  runPolicy:
    cleanPodPolicy: None
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          nodeSelector:
            kubernetes.io/hostname: xsailor-master
          containers:
          - name: pytorch
            image: potato4332/t5-fsdp:0.0.1
            imagePullPolicy: Always
            command:
              - "python"
            args:
              - "/workspace/t5-base.py"
              - "--dataset_url"
              - "https://public-nlp-datasets.s3.us-west-2.amazonaws.com/wikihowAll.csv"
              - "--model_name"
              - "t5-base"
              - "--num_samples"
              - "1500"
              - "--input_length"
              - "512"
              - "--output_length"
              - "150"
              - "--batch_size"
              - "4"
              - "--num_epochs"
              - "3"
              - "--learning_rate"
              - "0.002"
            env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: LOCAL_RANK
              value: "0"  
            - name: RANK
              value: "0"  
            - name: WORLD_SIZE
              value: "4"  
            - name: MASTER_ADDR
              value: "fsdp-t5-training-master-0"  
            - name: MASTER_PORT
              value: "29500"  
            resources:
              requests:
                cpu: 1
                nvidia.com/gpu: 1
              limits:
                cpu: 5
                nvidia.com/gpu: 1
    Worker:
      replicas: 3
      restartPolicy: Never
      template:
        spec:
          nodeSelector:
            kubernetes.io/hostname: xsailor-master
          containers:
          - name: pytorch
            image: potato4332/t5-fsdp:0.0.1
            imagePullPolicy: Always
            command:
              - "python"
            args:
              - "/workspace/t5-base.py"
              - "--dataset_url"
              - "https://public-nlp-datasets.s3.us-west-2.amazonaws.com/wikihowAll.csv"
              - "--model_name"
              - "t5-base"
              - "--num_samples"
              - "1500"
              - "--input_length"
              - "512"
              - "--output_length"
              - "150"
              - "--batch_size"
              - "4"
              - "--num_epochs"
              - "3"
              - "--learning_rate"
              - "0.002"
            env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: LOCAL_RANK
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['local-rank']
            - name: RANK
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['rank']
            - name: WORLD_SIZE
              value: "4"  
            - name: MASTER_ADDR
              value: "fsdp-t5-training-master-0"  
            - name: MASTER_PORT
              value: "29500"
            resources:
              requests:
                cpu: 1
                nvidia.com/gpu: 1
              limits:
                cpu: 5
                nvidia.com/gpu: 1
