# nfs-pv.yml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tfjob-nfs-storage
  labels:
    type: nfs
spec:
  capacity:
    storage: 900Gi
  accessModes: ["ReadWriteMany"]
  nfs:
    server: 163.152.20.207  
    path: /mnt/sdb/share_dir/tensorspot # NFS server's shared path

# nfs-pvc.yml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tfjob-nfs-storage-claim
spec:
  storageClassName: "" # null string -- important
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 900Gi
  selector:
    matchExpressions:
      - key: type
        operator: In
        values:
          - nfs
